### ISSUE TITLE
can't use cargo in this action

### ISSUE THREAD

**Issue by try-agaaain** [uraimo/run-on-arch-action#116]
I want to use this action to build a rust application on aarch64, but when I run cargo, this action will suddenly stop and exit. Frustratingly, no helpful prompts are given after exiting. [Failed action](https://github.com/try-agaaain/try-github-workflow/actions/runs/4416113741/jobs/7739970988)

![image](https://user-images.githubusercontent.com/52828870/225183990-944dba1c-5585-4375-956d-c42fb6a93cff.png)

By the way, I can build normally on my local aarch64 machine.

**Comment by martin-g** [comment]
The problem is that cargo tries to fetch the crates.io index and fails with OOM. It is a known issue!

See https://github.com/rust-lang/cargo/issues/10781#issuecomment-1351670409
Another solution is to use the new SPARSE protocol - https://blog.rust-lang.org/2023/03/09/Rust-1.68.0.html#cargos-sparse-protocol.

**Comment by uraimo** [comment]
Thanks @martin-g! Since with this we already have 2 issues related to Rust, it's probably time I'll start adding a specific section to the readme about solutions to common problems.

@try-agaaain can you confirm if this fixes the issue?

**Comment by try-agaaain** [comment]
Yes, it works fine now, thanks a lot.
