### ISSUE TITLE
Add support for subsequent actions

### ISSUE THREAD

**Issue by cornfeedhobo** [uraimo/run-on-arch-action#24]
The way this is written really limits the value of this action to only building artifacts, or so it seems. Is there any way to just prepare the build environment for the next action?

**Comment by elijahr** [comment]
As far as I am aware, this is not possible due to the way Github Actions work; the actions themselves can only be run on either GitHub's hosted runners, which are all x86 (Windows, Mac, or Linux), or your own [self-hosted runners](https://docs.github.com/en/free-pro-team@latest/actions/hosting-your-own-runners/about-self-hosted-runners). Self-hosted runners can be any network-accessible machine running the [Github Actions Runner](https://github.com/actions/runner/releases), which at this time officially supports x86 (Windows, Mac, or Linux), with the only alternative architecture being pre-release support for ARM & ARM64 Linux.

**Comment by elijahr** [comment]
If you want Linux ARM in the cloud to run your actions, you could provision an AWS A1 instance and install the Github Actions Runner as use that as a self-hosted runner for your project. I have not tested it. In that case, you wouldn't need run-on-arch-action. I have not done this myself, and there may be other options than AWS A1.

**Comment by uraimo** [comment]
Agree with @elijahr , If you mean executing some other action _inside the emulated context_ of container, that is not possible at the moment since it would require having all the GH Actions infrastructure runnable inside the container (with all that entails).
If you want to try some other cloud provider, it could make sense to give a try to Scaleway(lots of weird arm vps) or packet/equinix(arm64 servers) too.

**Comment by cornfeedhobo** [comment]
@uraimo I was worried this was the case.

@elijahr Running outside the GH infrastructure is out of the question in my case.

Thanks for the insights, both of you.
