### ISSUE TITLE
Building Images from Dockerfiles

### ISSUE THREAD

**Issue by rafal1137** [uraimo/run-on-arch-action#30]
When building image from Dockerfile it fails.

`> [2/3] COPY ./run-on-arch-install.sh /root/run-on-arch-install.sh:
  failed to compute cache key: "/run-on-arch-install.sh" not found: not found`

There is no such file in repo.

**Comment by elijahr** [comment]
@rafal1137 could you provide a link to your repo, or a workflow yaml file that can be used to reproduce the issue?

**Comment by elijahr** [comment]
FYI `run-on-arch-install.sh` is generated dynamically: https://github.com/uraimo/run-on-arch-action/blob/53ec774032a6fa253ad68cb3bd712681974652bc/src/run-on-arch.js#L51)

**Comment by rafal1137** [comment]
@elijahr Yes I was using your repo to build this container it was aarch64 ubuntu or buster.

**Comment by elijahr** [comment]
Ah, I think I might see what the issue is. So, the Dockerfiles are only ever used internally, by the action's scripts. The scripts set up the build context and create files such as `run-on-arch-install.sh`. The scripts are only known to run on a Github Actions runner. 

If you were to try to build a container locally using one of the Dockerfiles in this repo, it would fail because of missing scripts and so on. The Dockerfiles are thin wrappers around standard Docker containers. What are you trying to accomplish?

**Comment by rafal1137** [comment]
I wanted to investigate why cmake corrupts itself.
